<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Wmi;
use Illuminate\Database\Seeder;

class WmiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brandByWMI = [
            "South Africa"   => [
                "AAV" => "Volkswagen",
                "ADM" => "General Motors South Africa",
                "ADN" => "Nissan South Africa (Pty) Ltd",
                "AHT" => "Toyota",
                "AFA" => "Ford",
            ],
            "Kenya"          => [
                "BF9" => "KIBO Motorcycles",
            ],
            "Tunisia"        => [
                "CL9" => "Wallyscar",
            ],
            "Egypt"          => [
                "DA1" => "Egypt	Arab American Vehicles Company",
                "DA4" => "Egypt	Arab American Vehicles Company",
                "DAA" => "Fiat Auto Egypt Industrial Co",
                "DAB" => "BMW Egypt SKD",
            ],
            "Japan"          => [
                "J8B" => "Chevrolet",
                "JA4" => "Mitsubishi",
                "JAA" => "Isuzu",
                "JAL" => "Isuzu",
                "JAM" => "Isuzu",
                "JC1" => "Mazda",
                "JDA" => "Daihatsu",
                "JD1" => "Daihatsu",
                "JF1" => "Subaru - Fuji Heavy Industries",
                "JF2" => "Subaru - Fuji Heavy Industries",
                "JF3" => "Subaru - Fuji Heavy Industries",
                "JF4" => "Saab",
                "JF5" => "Pontiac",
                "JHD" => "Hino",
                "JHF" => "Hino",
                "JHH" => "Hino",
                "JHL" => "Honda",
                "JHM" => "Honda",
                "JL5" => "Mitsubishi",
                "JM0" => "Mazda for Oceania export",
                "JM1" => "Mazda",
                "JMB" => "Mitsubishi",
                "JM6" => "Mazda",
                "JN"  => "Nissan",
                "JS"  => "Suzuki",
                "JT"  => "Toyota/Lexus",
                "JY"  => "Yamaha",
            ],
            "South Korea"    => [
                "KL1" => "Daewoo",
                "KL2" => "Daewoo",
                "KLA" => "Daewoo",
                "KMA" => "Asia Motors Co Inc",
                "KMH" => "KM8	Hyundai",
                "KNA" => "Kia",
                "KNC" => "Kia",
                "KNE" => "Kia",
                "KNM" => "Samsung Motors Inc",
                "KPT" => "SsangYong",
            ],
            "China"          => [
                "L1C" => "Hubei Huawei Special-Purpose Automobile",
                "L2C" => "Chery Jaguar Land Rover",
                "L6T" => "Geely",
                "LA6" => "King Long",
                "LB3" => "Geely",
                "LBE" => "Beijing Hyundai",
                "LBV" => "BMW Brilliance",
                "LC0" => "BYD Industry",
                "LDC" => "Dongfeng Peugeot-Citroën",
                "LDN" => "South East Motor Co Ltd",
                "LE4" => "Beijing Benz",
                "LFA" => "Ford Lio Ho Motor Co Ltd",
                "LFM" => "FAW Toyota",
                "LFP" => "FAW Car",
                "LFV" => "FAW-Volkswagen",
                "LGB" => "Dongfeng Nissan",
                "LGJ" => "Dongfeng Fengshen",
                "LGW" => "Great Wall (Havel)",
                "LGX" => "BYD Auto",
                "LH1" => "FAW Haima",
                "LHG" => "Guangzhou Honda",
                "LJ1" => "JAC",
                "LJD" => "Dongfeng Yueda Kia",
                "LJU" => "Shanghai Maple Automobile Co.",
                "LLV" => "Lifan",
                "LMG" => "GAC Trumpchi",
                "LPA" => "Changan PSA (DS Automobiles)",
                "LPS" => "Polestar",
                "LS5" => "Changan Suzuki",
                "LRW" => "Tesla",
                "LSF" => "SAIC Maxus",
                "LSG" => "SAIC General Motors",
                "LSJ" => "SAIC MG",
                "LSV" => "SAIC Volkswagen",
                "LTV" => "FAW Toyota (Tianjin)",
                "LUX" => "Dongfeng Yulon Motor Co. Ltd",
                "LVG" => "GAC Toyota",
                "LVH" => "Dongfeng Honda",
                "LVR" => "Changan Mazda",
                "LVS" => "Changan Ford",
                "LVV" => "Chery",
                "LWV" => "GAC Fiat",
                "LZW" => "SAIC GM Wuling",
                "LZY" => "Yutong",
            ],
            "India"          => [
                "MA1" => "Mahindra",
                "MA3" => "Maruti Suzuki India Limited| Maruti| Suzuki",
                "MA6" => "General Motors India Pvt. Ltd.",
                "MA7" => "Hindustan Motors Ltd",
                "MAJ" => "Ford India Ltd.",
                "MAK" => "Honda Motor India Pvt. Ltd.",
                "MAL" => "Hyundai Motors India Ltd",
                "MAT" => "Tata Engineering & Locomotive Co",
                "MB1" => "Ashok Leyland Ltd",
                "MBH" => "Maruti Suzuki Automobiles India Limited",
                "MBJ" => "Toyota Kirloskar Motor Pvt Ltd",
                "MBK" => "MAN Truck & Bus India Pvt. Ltd",
                "MBU" => "Swaraj Vehicles Limited",
                "MBV" => "Premier Car World Pvt. Ltd",
                "MBY" => "Asia Motor Works good vehicle Ltd",
                "MC1" => "Force Motors Limited",
                "MC2" => "Eicher Motors Limited",
                "MC4" => "Dilip chhabria design pvt ltd",
                "MCA" => "FCA India Automobiles Pvt. Ltd",
                "MCB" => "General Motors India Pvt. Ltd.",
                "MCL" => "International Cars And Motors Ltd",
                "MD2" => "Bajaj Auto Ltd",
                "MDH" => "Nissan Motor India Pvt Ltd",
                "MEC" => "Daimler India Commercial Vehicles Pvt. Ltd.",
                "MEE" => "Renault Nissan Automobiles Pvt Ltd",
            ],
            "Indonesia"      => [
                "MH1" => "PT Astra Honda Motor",
            ],
            "Thailand"       => [
                "MLH" => "Thailand	Honda",
                "MM0" => "Mazda",
                "MM8" => "Mazda (Ford-Mazda AAT plant)",
                "MMB" => "Mitsubishi",
                "MMF" => "BMW",
                "MMH" => "Tata",
                "MMK" => "Toyota (Auto Works plant)",
                "MMM" => "Chevrolet",
                "MML" => "MG",
                "MMR" => "Subaru",
                "MMS" => "Suzuki",
                "MMT" => "Mitsubishi",
                "MNB" => "Ford (Ford-Mazda AAT plant)",
                "MNK" => "Hino Motors Manufacturing Thailand Co Ltd",
                "MNT" => "Nissan",
                "MPA" => "IMCT Isuzu Motors Company Thailand",
                "MPB" => "Ford (FTM plant)",
                "MP5" => "Foton",
                "MRH" => "Honda",
                "MR0" => "Toyota (Ban Pho and Samrong plant)",
                "MR2" => "Toyota (Gateway plant)",
            ],
            "Myanmar"        => [
                "MS0" => "Kia",
            ],
            "Iran"           => [
                "NAA" => "Irankhodro Company",
                "NAD" => "Saipa Diesel",
                "NAG" => "Bahman Industrial Group",
                "NAP" => "Pars Khodro",
            ],
            "Pakistan"       => [
                "NFB" => "Honda Atlas Cars Pakistan Ltd",
            ],
            "Turkey"         => [
                "NLC" => "Turkey Askam Kamyon Imalat Ve Tic.A.S.",
                "NMA" => "MAN",
                "NMT" => "Toyota",
                "NM0" => "Ford Otosan",
                "NM1" => "Oyak-Renault Oto Fab AS",
                "NM4" => "Tofas Turk Otomobil Fabrikasi AS",
            ],
            "Philippines"    => [
                "PAB" => "Isuzu Philippines Corporation",
            ],
            "Malaysia"       => [
                "PL1" => "Proton",
                "PL8" => "Hyundai/Inokom",
                "PLP" => "Subaru",
                "PLZ" => "ISUZU",
                "PMH" => "Honda",
                "PML" => "Hicom",
                "PM1" => "BMW",
                "PM2" => "Perodua",
                "PM9" => "Bufori",
                "PMK" => "Honda Boon Siew",
                "PMN" => "Modenas",
                "PMV" => "Yamaha Hong Leong",
                "PNA" => "Peugeot",
                "PNV" => "Volvo Cars",
                "PN2" => "Toyota",
                "PN1" => "Toyota",
                "PN8" => "Nissan",
                "PP1" => "Mazda",
                "PP3" => "Hyundai",
                "PPP" => "Suzuki",
                "PPV" => "Volkswagen",
                "PR8" => "Ford",
                "PRA" => "Sinotruk",
                "PRH" => "Chery",
            ],
            "Taiwan"         => [
                "RF5" => "Yulon Motor Co Ltd",
                "RFD" => "Tai Ling Motor Co Ltd",
                "RFG" => "SYM Motors",
                "RHA" => "Ford Lio Ho Motor Co Ltd",
                "RKJ" => "Prince Motors Taiwan",
                "RKL" => "Kuozui Motors",
                "RKM" => "China Motor Corporation",
                "RKT" => "Honda Taiwan",
            ],
            "Vietnam"        => [
                "RLE" => "Isuzu Vietnam Co Ltd"],
            "United Kingdom" => [
                "SA9" => "Morgan Motor Company",
                "SAB" => "Optare",
                "SAJ" => "Jaguar",
                "SAL" => "Land Rover",
                "SAR" => "Rover",
                "SAT" => "Triumph",
                "SB1" => "Toyota",
                "SBM" => "McLaren Automotive",
                "SC6" => "INEOS Automotive Limited",
                "SCC" => "Lotus Cars",
                "SCF" => "Aston Martin Lagonda Limited",
                "SCE" => "DeLorean",
                "SCK" => "Ifor Williams Trailers",
                "SDB" => "Talbot Motor Co Ltd",
                "SFD" => "Alexander Dennis",
                "SFE" => "Alexander Dennis (North America)",
                "SHH" => "Honda",
                "SHS" => "Honda",
                "SJK" => "Nissan",
                "SJN" => "Nissan",
            ],
            "Poland"         => [
                "SUD" => "Wielton",
                "SUP" => "Fabryka Samochodow Osobowych",
            ],
            "Switzerland"    => [
                "TCC" => "Micro Compact Car",
            ],
            "UK/Switzerland" => [
                "TEB" => "Johnston sweeper (Bucher)",
            ],
            "Czech Republic" => [
                "TMA" => "Hyundai",
                "TMB" => "Skoda",
            ],
            "Hungary"        => [
                "TRU" => "Audi",
                "TSM" => "Suzuki",
            ],
            "Portugal"       => [
                "TW8" => "General Motors De Portugal Lda",
            ],
            "Slovakia"       => [
                "U5Y" => "Kia",
            ],
            "Romania"        => [
                "UU" => "Dacia",
            ],
            "Austria"        => [
                "VA0" => "OAF",
                "VBK" => "KTM",
            ],
            "France"         => [
                "VF1" => "Renault",
                "VF2" => "Renault",
                "VF3" => "Peugeot",
                "VF4" => "Talbot",
                "VF5" => "Iveco Unic SA",
                "VF6" => "Renault Trucks/Volvo",
                "VF7" => "Citroën",
                "VF8" => "Matra/Talbot/Simca",
                "VF9" => "Bugatti",
                "VFE" => "IvecoBus",
                "VNK" => "Toyota",
                "VR1" => "DS Automobiles",
            ],
            "Spain"          => [
                "VS7" => "Citroen",
                "VSE" => "Santana Motor SA",
                "VSK" => "Nissan Motor Iberica SA, Nissan Passenger & Multi-Purpose Vehicle",
                "VSS" => "SEAT",
                "VSX" => "Opel Automobile Espana,SA",
                "VV9" => "Tauro Sport Auto",
            ],
            "Serbia"         => [
                "VX1" => "Sour Zavodi",
            ],
            "Germany"        => [
                "WAG"  => "Neoplan",
                "WAU"  => "Audi",
                "WAP"  => "Alpina",
                "WBA"  => "BMW",
                "WBS"  => "BMW M",
                "WBX"  => "BMW",
                "WDB"  => "Mercedes-Benz",
                "W1N"  => "Mercedes-Benz",
                "W1K"  => "Mercedes-Benz",
                "WDC"  => "DaimlerChrysler AG/Daimler AG",
                "WDD"  => "DaimlerChrysler AG/Daimler AG",
                "WMX"  => "DaimlerChrysler AG/Daimler AG",
                "WEB"  => "EvoBus",
                "WF0"  => "Ford of Europe",
                "WJM"  => "Iveco",
                "WJR"  => "Irmscher",
                "WKK"  => "Karl Kässbohrer Fahrzeugwerke",
                "WMA"  => "MAN",
                "WME"  => "Smart",
                "WMW"  => "Mini",
                "WP0"  => "Porsche car",
                "WP1"  => "Porsche SUV",
                "WUA"  => "Quattro",
                "WVG"  => "Volkswagen",
                "WVW"  => "Volkswagen",
                "WV1"  => "Volkswagen Commercial Vehicles",
                "WV2"  => "Volkswagen Commercial Vehicles",
                "W08"  => "Adam Opel AG Belgium",
                "W09"  => "Ruf Automobile",
                "W0L"  => "Opel/Vauxhall",
                "W0SV" => "Opel Special Vehicles",
            ],
            "Netherlands"    => [
                "XLR" => "DAF Trucks",
            ],
            "Russia"         => [
                "XTA" => "AvtoVAZ",
                "XTB" => "AZLK",
                "XU1" => "UAZ Special Purpose Vehicles Ltd",
                "XUF" => "General Motors Auto",
            ],
            "Uzbekistan"     => [
                "XWB" => "Daewoo GM Uzbekistan",
            ],
            "Ukraine"        => [
                "Y6D" => "Zaporiz'kyi avtozavod",
            ],
            "Finland"        => [
                "YK1" => "Saab",
            ],
            "Sweden"         => [
                "YS2" => "Scania, Södertälje",
                "YS3" => "Saab",
                "YS4" => "Scania, Katrineholm",
                "YTN" => "Saab NEVS",
                "YV1" => "Volvo Cars",
                "YV2" => "Volvo Trucks",
                "YV3" => "Volvo Buses",
                "YV4" => "Volvo",
                "YT9" => "Koenigsegg Automotive AB",
            ],
            "Italy"          => [
                "ZA9" => "Bugatti",
                "ZAA" => "Autobianchi",
                "ZAM" => "Maserati",
                "ZAP" => "Piaggio",
                "ZAR" => "Alfa Romeo",
                "ZCF" => "Iveco",
                "ZFA" => "Fiat",
                "ZFF" => "Ferrari",
                "ZGA" => "IvecoBus",
                "ZHW" => "Lamborghini",
                "ZLA" => "Lancia",
            ],
            "United States"  => [
                "1B"  => "Dodge",
                "1C"  => "Chrysler",
                "1F"  => "Ford",
                "1G"  => "General Motors",
                "1G1" => "Chevrolet",
                "1G3" => "Oldsmobile",
                "1G4" => "Buick",
                "1G9" => "Google",
                "1GB" => "Chevrolet incomplete vehicles",
                "1GC" => "Chevrolet",
                "1GD" => "GMC incomplete vehicles",
                "1GM" => "Pontiac",
                "1HG" => "Honda",
                "1J"  => "Jeep",
                "1L"  => "Lincoln",
                "1M"  => "Mercury",
                "1MR" => "Continental",
                "1N"  => "Nissan",
                "1VW" => "Volkswagen",
                "1YV" => "Mazda",
                "1ZV" => "Ford",
                "19U" => "Honda",
                "4S2" => "Isuzu Motors America Inc",
                "4S3" => "Subaru",
                "4S4" => "Subaru",
                "4S6" => "Honda",
                "5YJ" => "Tesla",
                "4US" => "BMW",
                "5FN" => "Honda",
                "5FR" => "Honda",
                "5G"  => "Hummer",
                "5J6" => "Honda",
                "5L"  => "Lincoln",
                "5N1" => "Nissan",
                "5NM" => "Hyundai",
                "5NP" => "Hyundai",
                "5T"  => "Toyota",
                "5U"  => "BMW",
                "5X"  => "Hyundai/Kia",
                "4T"  => "Toyota",
                "4F"  => "Mazda",
                "4J"  => "Mercedes-Benz",
                "4M"  => "Mercury",
                "7FA" => "Honda",
                "7JR" => "Volvo",
            ],
            "Canada"         => [
                "2DG" => "Drive & Gear",
                "2Gx" => "General Motors",
                "2G1" => "Chevrolet",
                "2G2" => "Pontiac",
                "2G9" => "Gnome Homes",
                "2HG" => "Honda",
                "2HH" => "Acura",
                "2HJ" => "Honda",
                "2HK" => "Honda",
                "2HM" => "Hyundai",
                "2L9" => "Les Contenants Durabac",
                "2LN" => "Lincoln",
                "2M"  => "Mercury",
                "2T"  => "Toyota",
                "2F"  => "Ford",
            ],
            "Mexico"         => [
                "3HG" => "Honda",
                "3HM" => "Honda",
                "3CZ" => "Honda",
                "3KP" => "Kia",
                "3MW" => "BMW",
                "3VW" => "Volkswagen",
                "3N"  => "Nissan",
                "3F"  => "Mexico Ford",
                "3G"  => "General Motors",
            ],
            "Australia"      => [
                "6F"  => "Ford",
                "6G"  => "General Motors",
                "6H"  => "Holden",
                "6G1" => "Chevrolet",
                "6G2" => "Pontiac",
                "6MM" => "Mitsubishi",
                "6T1" => "Toyota",
                "6T9" => "Trailer",
            ],
            "New Zealand"    => [
                "7A1" => "Mitsubishi",
                "7A3" => "Honda",
                "7A4" => "Toyota",
                "7A5" => "Ford",
                "7A8" => "NZ Transport Agency (pre-2009)",
                "7AT" => "NZ Transport Agency (post-2009)",
            ],
            "Bolivia"        => [
                "829" => "Quantum",
            ],
            "Argentina"      => [
                "8AP" => "Fiat",
                "8AF" => "Ford",
                "8AG" => "General Motors",
                "8AW" => "Volkswagen",
                "8AJ" => "Toyota",
                "8A1" => "Renault",
                "8AC" => "Mercedes Benz",
                "8BB" => "Agrale Argentina S.A",
                "8BC" => "Citroen",
                "8AD" => "Peugeot",
                "8AN" => "Nissan",
                "8C3" => "Honda",
                "8AT" => "Iveco",
            ],
            "Chile"          => [
                "8G1" => "Automotores Franco Chilena S.A",
                "8GD" => "Automotores Franco Chilena S.A",
                "8GG" => "General Motors Chile S.A",
            ],
            "Ecuador"        => [
                "8LB" => "General Motors OBB",
                "8LF" => "Maresa",
                "8LG" => "Aymesa",
            ],
            "Venezuela"      => [
                "8Z1" => "General Motors Venezolana C.A.",
            ],
            "Brazil"         => [
                "9AM" => "Massari",
                "9BD" => "Fiat Automóveis",
                "9BG" => "General Motors",
                "9BW" => "Volkswagen",
                "9BF" => "Ford",
                "93H" => "Honda",
                "9BR" => "Toyota",
                "936" => "Peugeot",
                "935" => "Citroen",
                "93P" => "Volare",
                "93Y" => "Renault",
                "93X" => "Souza Ramos - Mitsubishi / Suzuki",
                "9BH" => "Hyundai",
                "95P" => "CAOA / Hyundai",
                "94D" => "Nissan",
                "94G" => "Indabra",
                "94M" => "HVR-Busscar",
                "94N" => "RWM Brazil",
                "98R" => "Chery",
                "988" => "Jeep",
                "98M" => "BMW",
                "9BM" => "Mercedes-Benz",
                "9BN" => "Mafersa",
                "99A" => "Audi",
                "99L" => "BYD",
                "99J" => "Jaguar Land Rover",
                "9C2" => "Honda Motorcycles",
                "9C6" => "Yamaha",
                "9CD" => "Suzuki (motorcycles)",
                "93V" => "International Navistar",
                "93W" => "Fiat Professional",
                "93Z" => "Iveco",
                "953" => "VW Trucks / MAN",
                "9BS" => "Scania",
                "9BV" => "Volvo Trucks",
                "9BY" => "Agrale S/A",
            ],
            "Colombia"       => [
                "9FB" => "Renault",
                "9FC" => "Compañía Colombiana Automotriz S.A",
                "9GC" => "General Motors Colmotores S.A",
            ],
            "Uruguay"        => [
                "9UJ" => "Chery",
                "9UK" => "Lifan",
                "9UW" => "Kia",
            ],
        ];

        $inserts = [];
        foreach ($brandByWMI as $country => $wmis) {
            foreach ($wmis as $wmi => $brand) {
                $inserts[] = [
                    "wmi"        => $wmi,
                    "brand_id"   => Brand::where('brand', $brand)->first()->id,
                    "country"    => $country,
                    "created_at" => now(),
                    "updated_at" => now(),
                ];
            }
        }

        Wmi::insert($inserts);
    }
}
